# default parameters.

PATH:
  TRAIN_PATH: ./data/set_100ms/data_100ms_label4.npy
  TEST_PATH: ./data/set_100ms/test_100ms_label4.npy
  MODEL_PATH: ./results/model_100ms_label4.pth
HYPERPARAMS:
  MODELTYPE: 'LSTM'
  HIDDEN_SIZE: 128
  NUM_LAYERS: 2
  NUM_CLASSES: 4
  BATCH_SIZE: 64
  NUM_EPOCHS: 10
  LEARNING_RATE: 0.001
FEATUREPARAMS:
  SAMPLING_RATE: 44100
  NUM_CEPSTRAL_COEFFICIENTS: 40
  HOP_LENGTH: 512
  LEN_WINDOW: 2048