# default parameters.

PATH:
  TRAIN_PATH: ./data/audio_100ms/audio_train.npy
  TEST_PATH: ./data/audio_100ms/audio_test_0712_3_2.npy
  MODEL_PATH: ./results/LSTM_audio_only.pth
HYPERPARAMS:
  MODELTYPE: 'LSTM'
  HIDDEN_SIZE: 128
  NUM_LAYERS: 2
  NUM_CLASSES: 4
  BATCH_SIZE: 64
  NUM_EPOCHS: 10
  LEARNING_RATE: 0.001
  LABEL_CLASS: ['unknown','idling', 'cutting', 'hardcutting']
FEATUREPARAMS:
  SAMPLING_RATE: 44100
  NUM_CEPSTRAL_COEFFICIENTS: 40
  HOP_LENGTH: 512
  LEN_WINDOW: 2048