# parameters for train model

PATH:
  TRAIN_PATH: ./data/set_100ms/data_100ms_label4.npy
  MODEL_PATH: ./results/RNN_100ms.pth #this model will be made in path
HYPERPARAMS:
  MODELTYPE: 'RNN'
  HIDDEN_SIZE: 128
  NUM_LAYERS: 2
  NUM_CLASSES: 4
  BATCH_SIZE: 64
  NUM_EPOCHS: 10
  LEARNING_RATE: 0.001
  LABEL_CLASS: ['base','idling', 'cutting', 'hardcutting']
  LEN_FRAME: 100
FEATUREPARAMS:
  SAMPLING_RATE: 44100