# parameters for train model

PATH:
  TRAIN_PATH: ./data/set_100ms/data_100ms.npy
  MODEL_PATH: ./results/model_100ms.pth #this model will be made in path
HYPERPARAMS:
  HIDDEN_SIZE: 128
  NUM_LAYERS: 2
  NUM_CLASSES: 3
  BATCH_SIZE: 64
  NUM_EPOCHS: 10
  LEARNING_RATE: 0.001
  LABEL_CLASS: ['idling', 'cutting', 'hardcutting']
  LEN_FRAME: 100
FEATUREPARAMS:
  SAMPLING_RATE: 44100